const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#6C63FF",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#6C63FF",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#f0f0f0",
    tint: "#7C6FFF",
    background: "#0E0E16",
    foreground: "#f0f0f0",
    card: "#1A1A2E",
    cardForeground: "#f0f0f0",
    primary: "#7C6FFF",
    primaryForeground: "#ffffff",
    secondary: "#16213E",
    secondaryForeground: "#f0f0f0",
    muted: "#16213E",
    mutedForeground: "#888aaa",
    accent: "#6C63FF",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A4A",
    input: "#2A2A4A",
    gold: "#FFD700",
    correct: "#58CC02",
    incorrect: "#FF4B4B",
    surface: "#1E1E32",
  },
  radius: 12,
};

export default colors;
